services:
  db:
    profiles:
      - dev
    container_name: sonikswap_db
    image: postgres:17-alpine
    restart: unless-stopped
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sonikswap
    ports:
      - 5432:5432

  adminer:
    profiles:
      - dev
    image: adminer
    restart: always
    ports:
      - 8080:8080