[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio.workspace = true

axum = "0.7.9"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Business core
snk-core.workspace = true