[package]
name = "snk-core"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono.workspace = true
url.workspace = true
thiserror.workspace = true
uuid.workspace = true
serde.workspace = true

# Logging
tracing = "0.1.41"